### ISSUE TITLE
crash on tidy_and_resubmit on JUWELS

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_runscripts#15]
On JUWELS (`esm_master install-foci-default` and `esm_runscripts foci-juwels-initial-piCtl-daily-restart.yaml -e focitest` works fine) the `esm_runscripts foci-juwels-initial-piCtl-daily-restart.yaml -e focitest9 -t tidy_and_resubmit -p ${process} -j compute` crashes with the following error:
```bash
Started from:  /p/project/cesmtst/esmtst22/juwels/esm/esm-experiments/focitest9/scripts
starting :  tidy_and_resubmit
Traceback (most recent call last):
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1326, in recursive_get
    result = config_to_search[this_config]
KeyError: 'partition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1029, in resolve_basic_choose
    choice = recursive_get(config, path_to_key)
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1333, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1329, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/p/home/jusers/wahl1/juwels/.local/bin/esm_runscripts", line 10, in <module>
    sys.exit(main())
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_runscripts/cli.py", line 167, in main
    Setup = SimulationSetup(command_line_config)
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_runscripts/esm_sim_objects.py", line 50, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_runscripts/esm_sim_objects.py", line 241, in get_total_config_from_user_config
    esm_parser.choose_blocks(self.config, blackdict=self.config._blackdict)
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1993, in choose_blocks
    blackdict[model_with_choose]
  File "/p/home/jusers/wahl1/juwels/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1032, in resolve_basic_choose
    raise KeyError("Key %s was not defined", path_to_key)
KeyError: ('Key %s was not defined', ['computer', 'partition'])
```
The same setup works on mistral and HLRN Berlin. The `juwels.yaml` is based on `mistral.yaml`. I have checked `foci.yaml`, `juwels.yaml` and `foci-juwels-initial-piCtl-daily-restart.yaml ` several times, and don't have an explanation why this error occurs on JUWELS only. To reproduce on juwels
```bash
jutil env activate -p cesmtst
cd $PROJECT; mkdir esm; cd esm
mkdir models;
git clone -b add-blogin-support-and-CI-foci 	https://github.com/esm-tools/esm_tools.git
cd esm_tools
module load Python/3.6.8
./install.sh
esm_versions upgrade esm_environment=allow-source-workaround
esm_master install-foci-default # you need to get access to git.geomar.de before being able to do this
cd configs/foci
esm_runscripts foci-juwels-initial-piCtl-daily-restart.yaml -e focitest
```

**Comment by pgierz** [comment]
So, the error comes here:
```python
KeyError: ('Key %s was not defined', ['computer', 'partition'])
```

First off, we can write that down better. Try out the esm_parser branch "better_errors", I cleaned up (tiny) a bit. Maybe a better error would be:

```python
EsmParserError: ("Tried to find a definition for computer.partition (line X in the YAML file XYZ), but none was found!")
```

Getting the `computer.partition` to display nicely isn't so hard, but figuring out a way to put line number and file name of the file causing the error (which would be super useful) might be more (read: very) tricky. 

Does your `juwels.yaml` have a partition section? Doesn't look like it from what I can see in the release branch. Is the partition also called "compute"? If yes, then you probably just need to add this to juwels.yaml:

```yaml
partition: compute
```

and maybe all your problems will go away...

- - - -

As a side note:

There is another "template" library (which basically is what esm_parser is), Jinja2, that does 95% of what the parser already does, plus some extra things. This isn't for me to decide, but if we get rid of the parser and replace with that, we might save ourselves lots of headaches. It also does variable replacement (and points to line numbers in the yaml when it can't find something), mathematics, if statements, for loops, etc etc (all in yaml) The reason we didn't go with that from the beginning is that Dirk was hesitant to include third-party modules; that was before we figured out how to tell pip to instal 3rd party stuff for you.

Given that when something breaks, its 90% the parser, swapping this out for a battle-tested 3rd party solution might be extremely beneficial. But it'd really like to start doing science again...

**Comment by seb-wahl** [comment]
I tried setting `partition: compute` days ago. Did not help. After some print statements (I thought I'm past this), I figured that the `juwels.yaml` isn't used, because the pattern to recognise the machine in `all_machines.yaml` had a typo.

Regarding your side note: The MPI-ESM unscript generator is based on Jinja2 since more than 7 years: https://code.mpimet.mpg.de/projects/mkexp/wiki. We use mkexp since 5 years to run FOCI and/or MPI-ESM, so I do know it's pro's and con's a bit. Works a lot more with templates e.g. for the header of a batch script.

**Comment by seb-wahl** [comment]
...still a better error message could help. I'll suggest a fix in case no matching machine is found.

**Comment by pgierz** [comment]
@seb-wahl, I think that needs to go here:

https://github.com/esm-tools/esm_parser/blob/6ac597658419b3fe94ec219762e8f97b731c1489/esm_parser/esm_parser.py#L1631-L1671

There's already a warning message in there, and a commented out error. Maybe we should just raise that error, unless there is some sort of debug mode turned on.
