### ISSUE TITLE
Not copying the script to the EXP_PATH/scripts

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_runscripts#156]
@xshi-awi found a bug in `esm_runscripts` consisting in the following:

Trying to run `esm_runscripts <script.yaml> -e <exp_id>` from the `base_dir` (e.g. in mistral for me that is `/work/ab0246/a270152/esm_yaml_test/`) results in the `<script.yaml>` not being copied into the `<EXP_PATH>/scritps`. This of course breaks the whole simulation because ESM-Tools relays on readying the script from the experiment directory. If you try to run your runscript from a folder has some uncommon parents with the `scriptsdir` then everything works as it should.

I think the reason for that is one of the lines of the last patches in release:
https://github.com/esm-tools/esm_runscripts/blob/44e17e88a110507174461da435b63155725ab05e/esm_runscripts/compute.py#L508

If `from_dir` is in my case `/mnt/lustre02/work/ab0246/a270152/esm_yaml_test/`, cause my runscript is there, and `scriptsdir` is `/mnt/lustre02/work/ab0246/a270152/esm_yaml_test/xiaoxu/scripts`, then `scriptsdir_inside_fromdir` is gonna be true, i.e. `for p in pathlib.Path(scriptsdir).parents: p` returns the following:
```
PosixPath('/mnt/lustre02/work/ab0246/a270152/esm_yaml_test/xiaoxu')
PosixPath('/mnt/lustre02/work/ab0246/a270152/esm_yaml_test')
PosixPath('/mnt/lustre02/work/ab0246/a270152')
PosixPath('/mnt/lustre02/work/ab0246')
PosixPath('/mnt/lustre02/work')
PosixPath('/mnt/lustre02')
PosixPath('/mnt')
PosixPath('/')
```

As esm_runscripts is designed to run the runscript from the scripts directory my suggested solution is that we modify that line to be:
```
scriptsdir_inside_fromdir = pathlib.Path(fromdir) == pathlib.Path(scriptsdir)
```
What do you think @denizural , @dbarbi ?

**Versions used**
```
+---------------------+-----------+---------------------------------------------------------------+----------+-------------------+
| package_name        | version   | file                                                          | branch   | tags              |
|---------------------+-----------+---------------------------------------------------------------+----------+-------------------|
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_environment     | 5.1.1     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_master          | 5.1.3     | /mnt/lustre01/pf/a/a270152/esm_master                         | release  | v5.1.3-1-gde41278 |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_parser          | 5.1.6     | /mnt/lustre01/pf/a/a270152/esm_parser                         | release  | v5.1.6-1-g6264712 |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_runscripts      | 5.1.22    | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
| esm_tools           | 5.1.10    | /mnt/lustre01/pf/a/a270152/esm_tools                          | release  | v5.1.10           |
| esm_version_checker | 5.1.4     | /mnt/lustre01/pf/a/a270152/.local/lib/python3.6/site-packages |          |                   |
+---------------------+-----------+---------------------------------------------------------------+----------+-------------------+
```

**Comment by denizural** [comment]
Thanks @mandresm, for finding that. That line was preventing the esm-runscripts to enter an infinite recursion to create a directory structure inside the `scriptsdir`. I also have a solution. I will check that ASAP.

**Comment by mandresm** [comment]
Thanks :)

**Comment by denizural** [comment]
I think it should be fine at this point since the branch `hotfix/issue_156` has been merged to both `release` and `develop`. Since we are all busy about the new release, this issue can stay open until everything has been merged. Then, we can test again and close it.

**Comment by pgierz** [comment]
Hey, is this still relevant? I am trying to go through old issues and find things that can be closed so we can have a "clean slate" to start from with the next release. There is a merged PR, so, I hope not anymore relevant?

**Comment by mandresm** [comment]
Yes, this can be closed.
